### ISSUE TITLE
How to run CryptChat app server

### ISSUE THREAD

**Issue by AwaisIslam** [ejupialked/chat-diffie-hellman#3]
Hi, I hope you are well. Can you please tell me how to compile and run the CryptChat app server? I have run the client but the server is not working and I tried but don't how to do it. Please reply to me as I really need your help. It has to be compiled in Android Studio or any other tool like Netbeans.
![Capture](https://user-images.githubusercontent.com/30270675/99954737-0b74f480-2da5-11eb-8d00-e8303d561a3b.PNG)

**Comment by ejupialked** [comment]
Hi there,

Thanks for contacting me.

You should be able to run the main class in “sever/src/main/ServerApplication.java”

If you have issues please send a screenshot of the error message.

Kind Regards,
Alked

Kind Regards,
Alked Ejupi

________________________________

**Comment by AwaisIslam** [comment]
The issue is how I will run the "ServerApplication.java” class. I mean like we build the client app in Android Studio, similarly in which IDE I will build or run the Server side.
![Capture1](https://user-images.githubusercontent.com/30270675/99957007-d23e8380-2da8-11eb-890b-98f1fd2077cf.PNG)

**Comment by ejupialked** [comment]
The server code it's a Maven project and you can use something like IntelliJ IDEA to import it and install all required dependencies.

**Comment by AwaisIslam** [comment]
Ok can I use Eclipse IDE for it.

**Comment by AwaisIslam** [comment]
@ejupialked Thanks I have open the server in IntelliJ IDEA, but now how can I run it. Why is showing this red cross in the project?
![Capture](https://user-images.githubusercontent.com/30270675/99960155-197b4300-2dae-11eb-8144-c54dd6bcd9eb.PNG)

**Comment by AwaisIslam** [comment]
and can you tell me that I will use the same IP address and port number you used in demo or not

**Comment by ejupialked** [comment]
> and can you tell me that I will use the same IP address and port number you used in demo or not 

You can decide the port in the UI. The IP address should be your local host.

**Comment by ejupialked** [comment]
> @ejupialked Thanks I have open the server in IntelliJ IDEA, but now how can I run it. Why is showing this red cross in the project?
> 
> ![Capture](https://user-images.githubusercontent.com/30270675/99960155-197b4300-2dae-11eb-8144-c54dd6bcd9eb.PNG)
> 
> 
> @AwaisIslam  Right click that file and run it from there.

**Comment by AwaisIslam** [comment]
@ejupialked  It shows this when I right click on the file
![Capture1](https://user-images.githubusercontent.com/30270675/99963291-601f6c00-2db3-11eb-804b-2ce24feb2f7a.PNG)

**Comment by AwaisIslam** [comment]
@ejupialked It gave me this error when I click on the run button.

**Comment by ejupialked** [comment]
> @ejupialked It shows this when I right click on the file
> ![Capture1](https://user-images.githubusercontent.com/30270675/99963291-601f6c00-2db3-11eb-804b-2ce24feb2f7a.PNG)

You have set no JRE. Set one and see if it works.

**Comment by AwaisIslam** [comment]
@ejupialked thank you I have run the server.

**Comment by ejupialked** [comment]
> @ejupialked thank you I have run the server.

Let me know if you have other issues. Feel free to improve the code and open a pull request. 😄
